(()=>{"use strict";
const $=id=>document.getElementById(id),N=x=>String(x??"").trim(),K=x=>N(x).toUpperCase();
const normPath=t=>{t=t.replace(/^\/+/,"");return t.startsWith("xl/")?t:"xl/"+t.replace(/^(\.\.\/)+/,"")};
const esc=s=>N(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
function rows(ws,headerRow=1){const a=XLSX.utils.sheet_to_json(ws,{header:1,defval:"",raw:true});if(a.length<headerRow)return null;const h=a[headerRow-1].map(K);return{head:h,rows:a.slice(headerRow).map((r,i)=>({row:i+headerRow+1,values:r}))};}
function col(info,names){for(const n of names){const i=info.head.indexOf(K(n));if(i>=0)return i}return -1;}
function keepSet(info,ins,per){const ic=col(info,["INSPECTOR"]),pc=col(info,["PERIODO","PERIODO / MES"]),keep=new Set([1]);for(const r of info.rows){const i=ic>=0?N(r.values[ic]):"",p=pc>=0?N(r.values[pc]):"";if(ic>=0&&ins&&K(i)!==K(ins))continue;if(pc>=0&&per&&K(p)!==K(per))continue;keep.add(r.row)}return keep;}
function hideRows(xml,keep){return xml.replace(/<row\b[^>]*>/g,m=>{const n=Number((m.match(/\br="(\d+)"/)||[])[1]);if(!n||keep.has(n))return m;return /\bhidden="/.test(m)?m.replace(/\bhidden="[^"]*"/,'hidden="1"'):m.replace(/>$/,' hidden="1">')});}
async function sheetPaths(zip){const wx=await zip.file("xl/workbook.xml").async("string"),rx=await zip.file("xl/_rels/workbook.xml.rels").async("string"),rd=new DOMParser().parseFromString(rx,"application/xml"),rels={};for(const e of Array.from(rd.getElementsByTagName("Relationship")))rels[e.getAttribute("Id")]=e.getAttribute("Target");const wd=new DOMParser().parseFromString(wx,"application/xml"),out={};for(const e of Array.from(wd.getElementsByTagName("sheet"))){const id=e.getAttribute("r:id")||e.getAttributeNS("http://schemas.openxmlformats.org/officeDocument/2006/relationships","id");if(id&&rels[id])out[e.getAttribute("name")]=normPath(rels[id])}return{workbook:wx,rels,paths:out}}
function removeMacros(ct,rels,zip){for(const name of Object.keys(zip.files)){if(/^xl\/(vbaProject|vbaData|vbaProjectSignature)/i.test(name)||/^customUI\//i.test(name))zip.remove(name)}rels=rels.replace(/<Relationship\b[^>]*(?:vbaProject|vbaProjectSignature|customUI|calcChain)[^>]*\/?>/gi,"");ct=ct.replace(/<Override\b[^>]*(?:vbaProject|vbaProjectSignature|calcChain)[^>]*\/?>/gi,"");ct=ct.replace(/<Default\b[^>]*Extension=["']bin["'][^>]*ContentType=["']application\/vnd\.ms-office\.vbaProject["'][^>]*\/?>/gi,"");ct=ct.replace(/application\/vnd\.ms-excel\.sheet\.macroEnabled\.main\+xml/gi,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml");return{ct,rels}}
function removeControl(workbook,rels,zip){const m=workbook.match(/<sheet\b[^>]*\bname=["']CONTROL["'][^>]*\/?>/i);if(!m)return{workbook,rels};const rid=(m[0].match(/\br:id=["']([^"']+)["']/)||[])[1];workbook=workbook.replace(m[0],"");if(rid){const re=new RegExp(`<Relationship\\b[^>]*\\bId=["']${rid}["'][^>]*/?>`,'i'),rm=rels.match(re);if(rm){const target=(rm[0].match(/\bTarget=["']([^"']+)["']/i)||[])[1];if(target)zip.remove(normPath(target));rels=rels.replace(re,"")}}workbook=workbook.replace(/<definedName\b[^>]*>[^<]*(?:CONTROL|control)!.*?<\/definedName>/gis,"");return{workbook,rels}}
function sanitizeWorkbook(workbook){workbook=workbook.replace(/<calcPr\b[^>]*\/?>/i,"");return workbook}
async function cleanOriginal(file,ins,per){const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:"array",cellDates:true}),z=await JSZip.loadAsync(buf),meta=await sheetPaths(z);let workbook=meta.workbook,rels=meta.rels,ct=await z.file("[Content_Types].xml").async("string");({workbook,rels}=removeControl(workbook,rels,z));({ct,rels}=removeMacros(ct,rels,z));workbook=sanitizeWorkbook(workbook);
for(const name of ["DETALLE","MAT","RECUPERO"]){const real=wb.SheetNames.find(x=>K(x)===name);if(!real||!meta.paths[real])continue;const info=rows(wb.Sheets[real,/^(MAT|RECUPERO)$/.test(name)?9:1]);if(!info)continue;z.file(meta.paths[real],hideRows(await z.file(meta.paths[real]).async("string"),keepSet(info,ins,per)))}
const datos=wb.SheetNames.find(x=>K(x)==="DATOS");if(datos&&meta.paths[datos]){const cleanValue=(xml,ref,value)=>{const re=new RegExp(`<c\\b[^>]*\\br="${ref}"[^>]*>.*?<\\/c>`,'s'),m=xml.match(re);if(!m)return xml;const style=(m[0].match(/\bs="([^"]+)"/)||[])[1];return xml.replace(re,`<c r="${ref}"${style?` s="${style}"`:""} t="inlineStr"><is><t>${esc(value)}</t></is></c>`)};let x=await z.file(meta.paths[datos]).async("string");x=cleanValue(x,"B14",ins);x=cleanValue(x,"B28",per);z.file(meta.paths[datos],x)}
// No se modifica la lógica/formato de TAPA aquí: se conserva la versión ya preparada por app.js.
z.file("xl/workbook.xml",workbook);z.file("xl/_rels/workbook.xml.rels",rels);z.file("[Content_Types].xml",ct);return await z.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}})}
async function exportClean(){const file=$("file")?.files?.[0],ins=$("ins")?.value||"",per=$("per")?.value||"";if(!file)return alert("Carga primero el archivo Excel.");if(!ins||!per)return alert("Selecciona Inspector y Periodo antes de generar la liquidación.");if(!window.JSZip)return alert("No se cargó el motor de Excel. Actualiza la página.");if(!/\.(xlsx|xlsm)$/i.test(file.name))return alert("La salida exacta requiere .xlsx o .xlsm.");try{const out=await cleanOriginal(file,ins,per),a=document.createElement("a");a.href=URL.createObjectURL(out);a.download=file.name.replace(/\.(xlsm|xlsb|xlsx)$/i,"")+` - ${ins.replace(/\s+/g,"_")} - ${per.replace(/\s+/g,"_")}.xlsx`;a.style.display="none";document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200);$("badge").textContent="Archivo generado sin macros";$("prevbox").textContent=`Liquidación ${ins} · ${per} generada en .xlsx, sin macros y sin hoja CONTROL.`}catch(e){console.error(e);alert("No se pudo generar el Excel limpio: "+(e.message||e))}}
document.addEventListener("click",e=>{const t=e.target?.closest?.("#gen,#exp");if(!t)return;e.preventDefault();e.stopImmediatePropagation();exportClean()},true);
})();