(()=>{
"use strict";
const $=id=>document.getElementById(id);
const N=x=>String(x??"").trim(), K=x=>N(x).toUpperCase();
const normPath=t=>{t=t.replace(/^\/+/,"");return t.startsWith("xl/")?t:"xl/"+t.replace(/^(\.\.\/)+/,"")};
const esc=s=>N(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
function sheetRows(ws,headerRow){const a=XLSX.utils.sheet_to_json(ws,{header:1,defval:"",raw:true});if(a.length<headerRow)return null;const h=a[headerRow-1].map(K);return{head:h,rows:a.slice(headerRow).map((r,i)=>({row:i+headerRow+1,values:r}))};}
function col(info,names){for(const n of names){const i=info.head.indexOf(K(n));if(i>=0)return i}return -1;}
function keepSet(info,ins,per){const ic=col(info,["INSPECTOR"]),pc=col(info,["PERIODO","PERIODO / MES"]),keep=new Set([1]);for(const r of info.rows){const rvIns=ic>=0?N(r.values[ic]):"",rvPer=pc>=0?N(r.values[pc]):"";let ok=true;if(ic>=0&&ins&&K(rvIns)!==K(ins))ok=false;if(pc>=0&&per&&K(rvPer)!==K(per))ok=false;if(ok)keep.add(r.row)}return keep;}
function hideRows(xml,keep){return xml.replace(/<row\b[^>]*>/g,m=>{const n=Number((m.match(/\br="(\d+)"/)||[])[1]);if(!n||keep.has(n))return m;return /\bhidden="/.test(m)?m.replace(/\bhidden="[^"]*"/,'hidden="1"'):m.replace(/>$/,' hidden="1">')});}
async function paths(zip){const wx=await zip.file("xl/workbook.xml").async("string"),rx=await zip.file("xl/_rels/workbook.xml.rels").async("string");const rd=new DOMParser().parseFromString(rx,"application/xml"),rels={};for(const e of Array.from(rd.getElementsByTagName("Relationship")))rels[e.getAttribute("Id")]=e.getAttribute("Target");const wd=new DOMParser().parseFromString(wx,"application/xml"),out={};for(const e of Array.from(wd.getElementsByTagName("sheet"))){const id=e.getAttribute("r:id")||e.getAttributeNS("http://schemas.openxmlformats.org/officeDocument/2006/relationships","id");if(id&&rels[id])out[e.getAttribute("name")]=normPath(rels[id])}return{workbook:wx,rels,paths:out};}
function removeControlSheet(workbookXml,relsXml,paths,zip){const m=workbookXml.match(/<sheet\b[^>]*\bname=["']CONTROL["'][^>]*\/>/i);if(!m)return{workbookXml,relsXml};const sheet=m[0],rid=(sheet.match(/\br:id=["']([^"']+)["']/)||[])[1];workbookXml=workbookXml.replace(sheet,"");if(rid){const relRe=new RegExp(`<Relationship\\b[^>]*\\bId=["']${rid}["'][^>]*/>`,'i'),relm=relsXml.match(relRe);if(relm){relsXml=relsXml.replace(relm[0],"");const target=(relm[0].match(/\bTarget=["']([^"']+)["']/i)||[])[1];if(target)zip.remove(normPath(target));}}
workbookXml=workbookXml.replace(/<definedName\b[^>]*>[^<]*(?:CONTROL|Control)[^<]*<\/definedName>/gi,"");return{workbookXml,relsXml};}
function removeMacros(contentTypesXml,workbookXmlRels,zip){zip.remove("xl/vbaProject.bin");zip.remove("xl/vbaProjectSignature.bin");workbookXmlRels=workbookXmlRels.replace(/<Relationship\b[^>]*(?:vbaProject|vbaProjectSignature)[^>]*\/>/gi,"");contentTypesXml=contentTypesXml.replace(/<Override\b[^>]*(?:vbaProject|vbaProjectSignature)[^>]*/gi,"");contentTypesXml=contentTypesXml.replace(/<Override\b[^>]*PartName=["']\/xl\/workbook\.xml["'][^>]*ContentType=["']application\/vnd\.ms-excel\.sheet\.macroEnabled\.main\+xml["'][^>]*\/>/i,`<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>`);contentTypesXml=contentTypesXml.replace(/<Default\b[^>]*Extension=["']bin["'][^>]*/gi,m=>/vba/i.test(m)?"":m);return{contentTypesXml,workbookXmlRels};}
function stripMacroExtension(name){return name.replace(/\.(xlsm|xlsb)$/i,"")+'.xlsx'}
function formula(xml,ref,f){const re=new RegExp(`<c\\b[^>]*\\br="${ref}"[^>]*>.*?<\\/c>`,'s'),m=xml.match(re);if(!m)return xml;const st=(m[0].match(/\bs="([^"]+)"/)||[])[1];return xml.replace(re,`<c r="${ref}"${st?` s="${st}"`:""}><f>${f}</f><v></v></c>`)}
function inline(xml,ref,value){const re=new RegExp(`<c\\b[^>]*\\br="${ref}"[^>]*>.*?<\\/c>`,'s'),m=xml.match(re);if(!m)return xml;const st=(m[0].match(/\bs="([^"]+)"/)||[])[1];return xml.replace(re,`<c r="${ref}"${st?` s="${st}"`:""} t="inlineStr"><is><t>${esc(value)}</t></is></c>`)}
function buildTapa(xml,detailLast,matLast,recLast){const count=(r,t)=>`COUNTIFS(DETALLE!$Q$2:$Q$${detailLast},$C${r},DETALLE!$C$2:$C$${detailLast},"${t}",DETALLE!$X$2:$X$${detailLast},DATOS!$B$14,DETALLE!$L$2:$L$${detailLast},DATOS!$B$28)`;for(let r=24;r<=29;r++){xml=formula(xml,`J${r}`,count(r,"TELECONTROL"));xml=formula(xml,`L${r}`,`IFERROR(J${r}*K${r},0)`)}for(let r=36;r<=39;r++){xml=formula(xml,`J${r}`,count(r,"PROTECCION"));xml=formula(xml,`L${r}`,`IFERROR(J${r}*K${r},0)`)}for(let r=46;r<=48;r++){xml=formula(xml,`J${r}`,`SUMIFS(MAT!$J$10:$J$${matLast},MAT!$E$10:$E$${matLast},$C${r},MAT!$O$10:$O$${matLast},DATOS!$B$14,MAT!$P$10:$P$${matLast},DATOS!$B$28)`);xml=formula(xml,`L${r}`,`IFERROR(J${r}*K${r},0)`)}for(let r=55;r<=59;r++){xml=formula(xml,`J${r}`,`SUMIFS(RECUPERO!$I$10:$I$${recLast},RECUPERO!$E$10:$E$${recLast},$C${r},RECUPERO!$L$10:$L$${recLast},DATOS!$B$14,RECUPERO!$M$10:$M$${recLast},DATOS!$B$28)`);xml=formula(xml,`L${r}`,`IFERROR(J${r}*K${r},0)`)}return xml}
async function exportClean(){const file=$("file")?.files?.[0];const ins=$("ins")?.value||"",per=$("per")?.value||"";if(!file)return alert("Carga primero el archivo Excel.");if(!ins||!per)return alert("Selecciona Inspector y Periodo antes de generar la liquidación.");if(!window.JSZip)return alert("No se cargó el motor de Excel. Actualiza la página.");if(!/\.(xlsx|xlsm)$/i.test(file.name))return alert("La salida exacta requiere .xlsx o .xlsm.");try{const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:"array",cellDates:true}),z=await JSZip.loadAsync(buf),meta=await paths(z);let wxml=meta.workbook,rxml=await z.file("xl/_rels/workbook.xml.rels").async("string"),ct=await z.file("[Content_Types].xml").async("string");const control=wb.SheetNames.find(x=>K(x)==="CONTROL");if(control&&meta.paths[control])z.remove(meta.paths[control]);({workbookXml:wxml,relsXml:rxml}=removeControlSheet(wxml,rxml,meta.paths,z));({contentTypesXml:ct,workbookXmlRels:rxml}=removeMacros(ct,rxml,z));
for(const name of ["DETALLE","MAT","RECUPERO"]){const real=wb.SheetNames.find(x=>K(x)===name);if(!real||!meta.paths[real])continue;const sheetData=sheetRows(wb.Sheets[real],/^(MAT|RECUPERO)$/.test(name)?9:1);if(!sheetData)continue;z.file(meta.paths[real],hideRows(await z.file(meta.paths[real]).async("string"),keepSet(sheetData,ins,per)))}
const datos=wb.SheetNames.find(x=>K(x)==="DATOS");if(datos&&meta.paths[datos]){let x=await z.file(meta.paths[datos]).async("string");x=inline(x,"B14",ins);x=inline(x,"B28",per);z.file(meta.paths[datos],x)}
const tapa=wb.SheetNames.find(x=>K(x)==="TAPA"),det=wb.SheetNames.find(x=>K(x)==="DETALLE"),mat=wb.SheetNames.find(x=>K(x)==="MAT"),rec=wb.SheetNames.find(x=>K(x)==="RECUPERO");if(tapa&&meta.paths[tapa]){const lr=w=>XLSX.utils.decode_range(w?.["!ref"]||"A1:A1").e.r+1;let x=await z.file(meta.paths[tapa]).async("string");x=buildTapa(x,lr(wb.Sheets[det]),lr(wb.Sheets[mat]),lr(wb.Sheets[rec]));z.file(meta.paths[tapa],x)}
wxml=wxml.replace(/<calcPr\b[^>]*\/>/i,`<calcPr calcId="191029" calcMode="auto" fullCalcOnLoad="1" forceFullCalc="1" calcOnSave="1"/>`);if(!/<calcPr\b/i.test(wxml))wxml=wxml.replace("</workbook>",`<calcPr calcId="191029" calcMode="auto" fullCalcOnLoad="1" forceFullCalc="1" calcOnSave="1"/></workbook>`);z.file("xl/workbook.xml",wxml);z.file("xl/_rels/workbook.xml.rels",rxml);z.file("[Content_Types].xml",ct);const out=await z.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}});const a=document.createElement("a");a.href=URL.createObjectURL(out);a.download=stripMacroExtension(file.name).replace(/\.xlsx$/i,"")+` - ${ins.replace(/\s+/g,"_")} - ${per.replace(/\s+/g,"_")}.xlsx`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200);$("badge").textContent="Archivo generado sin macros";$("prevbox").textContent=`Liquidación ${ins} · ${per} generada en .xlsx, sin macros y sin hoja CONTROL.`;}
catch(e){console.error(e);alert("No se pudo generar el Excel limpio: "+(e.message||e))}}
// Intercepta los botones existentes para garantizar salida .xlsx sin VBA ni CONTROL.
document.addEventListener("click",e=>{const t=e.target?.closest?.("#gen,#exp");if(!t)return;e.preventDefault();e.stopImmediatePropagation();exportClean()},true);
})();