(()=>{"use strict";
const $=id=>document.getElementById(id),N=x=>String(x??"").trim(),K=x=>N(x).toUpperCase();
const normPath=t=>{t=t.replace(/^\/+/,"");return t.startsWith("xl/")?t:"xl/"+t.replace(/^(\.\.\/)+/,"")};
const esc=s=>N(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
function rows(ws,headerRow=1){const a=XLSX.utils.sheet_to_json(ws,{header:1,defval:"",raw:true});if(a.length<headerRow)return null;const h=a[headerRow-1].map(K);return{head:h,rows:a.slice(headerRow).map((r,i)=>({row:i+headerRow+1,values:r}))};}
function col(info,names){for(const n of names){const i=info.head.indexOf(K(n));if(i>=0)return i}return -1}
function keepSet(info,ins,per){const ic=col(info,["INSPECTOR"]),pc=col(info,["PERIODO","PERIODO / MES"]),keep=new Set([1]);for(const r of info.rows){const i=ic>=0?N(r.values[ic]):"",p=pc>=0?N(r.values[pc]):"";if(ic>=0&&ins&&K(i)!==K(ins))continue;if(pc>=0&&per&&K(p)!==K(per))continue;keep.add(r.row)}return keep}
function hideRows(xml,keep){return xml.replace(/<row\b[^>]*>/g,m=>{const n=Number((m.match(/\br="(\d+)"/)||[])[1]);if(!n||keep.has(n))return m;return /\bhidden="/.test(m)?m.replace(/\bhidden="[^"]*"/,'hidden="1"'):m.replace(/>$/,' hidden="1">')})}
async function getMeta(zip){const workbook=await zip.file("xl/workbook.xml").async("string"),relsXml=await zip.file("xl/_rels/workbook.xml.rels").async("string"),doc=new DOMParser().parseFromString(relsXml,"application/xml"),map={};for(const e of Array.from(doc.getElementsByTagName("Relationship")))map[e.getAttribute("Id")]=e.getAttribute("Target");const wdoc=new DOMParser().parseFromString(workbook,"application/xml"),paths={};for(const e of Array.from(wdoc.getElementsByTagName("sheet"))){const id=e.getAttribute("r:id")||e.getAttributeNS("http://schemas.openxmlformats.org/officeDocument/2006/relationships","id");if(id&&map[id])paths[e.getAttribute("name")]=normPath(map[id])}return{workbook,relsXml,paths}}
function removeControl(workbookXml,relsXml,zip){const m=workbookXml.match(/<sheet\b[^>]*\bname=["']CONTROL["'][^>]*\/?>/i);if(!m)return{workbookXml,relsXml};const rid=(m[0].match(/\br:id=["']([^"']+)["']/)||[])[1];workbookXml=workbookXml.replace(m[0],"");if(rid){const re=new RegExp(`<Relationship\\b[^>]*\\bId=["']${rid}["'][^>]*/?>`,'i');const rm=relsXml.match(re);if(rm){const target=(rm[0].match(/\bTarget=["']([^"']+)["']/i)||[])[1];if(target)zip.remove(normPath(target));relsXml=relsXml.replace(re,"")}}return{workbookXml,relsXml}}
function removeMacroParts(ct,relsXml,zip){for(const name of Object.keys(zip.files)){if(/^xl\/(vbaProject|vbaData|vbaProjectSignature)/i.test(name)||/^customUI\//i.test(name))zip.remove(name)}relsXml=relsXml.replace(/<Relationship\b[^>]*(?:vbaProject|vbaProjectSignature|customUI|calcChain)[^>]*\/?>/gi,"");ct=ct.replace(/<Override\b[^>]*(?:vbaProject|vbaProjectSignature|calcChain)[^>]*\/?>/gi,"");ct=ct.replace(/<Default\b[^>]*Extension=["']bin["'][^>]*ContentType=["']application\/vnd\.ms-office\.vbaProject["'][^>]*\/?>/gi,"");ct=ct.replace(/<Override\b[^>]*PartName=["']\/xl\/workbook\.xml["'][^>]*ContentType=["']application\/vnd\.ms-excel\.sheet\.macroEnabled\.main\+xml["'][^>]*\/?>/i,`<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>`);return{ct,relsXml}}
function removeExternalLinks(workbookXml,relsXml,ct,zip){for(const name of Object.keys(zip.files)){if(/^xl\/externalLinks\//i.test(name)||/^xl\/calcChain\.xml$/i.test(name))zip.remove(name)}relsXml=relsXml.replace(/<Relationship\b[^>]*(?:externalLink|externalLinks|calcChain)[^>]*\/?>/gi,"");workbookXml=workbookXml.replace(/<externalReferences\b[\s\S]*?<\/externalReferences>/gi,"");ct=ct.replace(/<Override\b[^>]*(?:externalLink|externalLinks|calcChain)[^>]*\/?>/gi,"");return{workbookXml,relsXml,ct}}
function cleanExternalFormulaCells(xml){return xml.replace(/<c\b([^>]*)>[\s\S]*?<f\b[^>]*>([\s\S]*?\[[^\]]+\][\s\S]*?)<\/f>[\s\S]*?<v>([\s\S]*?)<\/v>[\s\S]*?<\/c>/gi,(full,attrs,formula,value)=>value!==""?`<c${attrs}><v>${value}</v></c>`:full)}
function cleanCell(xml,ref,value){const re=new RegExp(`<c\\b[^>]*\\br="${ref}"[^>]*>[\\s\\S]*?<\\/c>`,'s'),m=xml.match(re);if(!m)return xml;const s=(m[0].match(/\bs="([^"]+)"/)||[])[1];return xml.replace(re,`<c r="${ref}"${s?` s="${s}"`:""} t="inlineStr"><is><t>${esc(value)}</t></is></c>`)}
function disableWrapInDetailStyles(stylesXml,detailXml){const m=stylesXml.match(/<cellXfs\b[^>]*>([\s\S]*?)<\/cellXfs>/i);if(!m)return{stylesXml,detailXml};const xfs=m[1].match(/<xf\b(?:[^>]*\/>|[^>]*>[\s\S]*?<\/xf>)/gi)||[];const map={},clones=[];xfs.forEach((xf,i)=>{if(/<alignment\b[^>]*\bwrapText=["']1["']/i.test(xf)){const clone=xf.replace(/\s+wrapText=["']1["']/gi,"");if(clone!==xf){map[i]=xfs.length+clones.length;clones.push(clone)}}});if(!clones.length)return{stylesXml,detailXml};const newCount=xfs.length+clones.length;const opening=m[0].replace(/\bcount="\d+"/i,`count="${newCount}"`);stylesXml=stylesXml.replace(m[0],`${opening}${xfs.join("")}${clones.join("")}</cellXfs>`);detailXml=detailXml.replace(/<c\b[^>]*\bs="(\d+)"[^>]*>/gi,(full,s)=>Object.prototype.hasOwnProperty.call(map,s)?full.replace(/\bs="\d+"/,`s="${map[s]}"`):full);return{stylesXml,detailXml}}
async function prepareDetailNoWrap(zip,detailPath){const sf=zip.file("xl/styles.xml"),df=zip.file(detailPath);if(!sf||!df)return;const out=disableWrapInDetailStyles(await sf.async("string"),await df.async("string"));zip.file("xl/styles.xml",out.stylesXml);zip.file(detailPath,out.detailXml)}
async function buildOutput(file,ins,per){const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:"array",cellDates:true}),zip=await JSZip.loadAsync(buf),meta=await getMeta(zip);let workbookXml=meta.workbook,relsXml=meta.relsXml,ct=await zip.file("[Content_Types].xml").async("string");({workbookXml,relsXml}=removeControl(workbookXml,relsXml,zip));({ct,relsXml}=removeMacroParts(ct,relsXml,zip));({workbookXml,relsXml,ct}=removeExternalLinks(workbookXml,relsXml,ct,zip));
for(const name of ["DETALLE","MAT","RECUPERO"]){const real=wb.SheetNames.find(x=>K(x)===name);if(!real||!meta.paths[real])continue;const info=rows(wb.Sheets[real,/^(MAT|RECUPERO)$/.test(name)?9:1]);if(!info)continue;let xml=hideRows(await zip.file(meta.paths[real]).async("string"),keepSet(info,ins,per));if(name==="DETALLE")xml=cleanExternalFormulaCells(xml);zip.file(meta.paths[real],xml)}
for(const real of wb.SheetNames){if(!meta.paths[real]||/^(DETALLE|MAT|RECUPERO)$/.test(K(real)))continue;const f=zip.file(meta.paths[real]);if(!f)continue;const xml=await f.async("string");if(xml.includes("<f")&&xml.includes("["))zip.file(meta.paths[real],cleanExternalFormulaCells(xml))}
const datos=wb.SheetNames.find(x=>K(x)==="DATOS");if(datos&&meta.paths[datos]){let xml=await zip.file(meta.paths[datos]).async("string");xml=cleanCell(xml,"B14",ins);xml=cleanCell(xml,"B28",per);zip.file(meta.paths[datos],xml)}
if(meta.paths["DETALLE"])await prepareDetailNoWrap(zip,meta.paths["DETALLE"]);workbookXml=workbookXml.replace(/<calcPr\b[^>]*\/?>/i,"");zip.file("xl/workbook.xml",workbookXml);zip.file("xl/_rels/workbook.xml.rels",relsXml);zip.file("[Content_Types].xml",ct);return zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}})}
async function exportClean(){const file=$("file")?.files?.[0],ins=$("ins")?.value||"",per=$("per")?.value||"";if(!file)return alert("Carga primero el archivo Excel.");if(!ins||!per)return alert("Selecciona Inspector y Periodo antes de generar la liquidación.");if(!window.JSZip)return alert("No se cargó el motor de Excel. Actualiza la página.");try{const out=await buildOutput(file,ins,per),a=document.createElement("a");a.href=URL.createObjectURL(out);a.download=file.name.replace(/\.(xlsm|xlsb|xlsx)$/i,"")+` - ${ins.replace(/\s+/g,"_")} - ${per.replace(/\s+/g,"_")}.xlsx`;a.style.display="none";document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200);$("badge").textContent="Archivo limpio generado";$("prevbox").textContent=`Liquidación ${ins} · ${per} generada en .xlsx, sin macros, sin CONTROL y sin vínculos externos.`}catch(e){console.error(e);alert("No se pudo generar el Excel limpio: "+(e.message||e))}}
document.addEventListener("click",e=>{const t=e.target?.closest?.("#gen,#exp");if(!t)return;e.preventDefault();e.stopImmediatePropagation();exportClean()},true);
})();