(()=>{"use strict";
const $=id=>document.getElementById(id),N=x=>String(x??"").trim(),K=x=>N(x).toUpperCase();
const normPath=t=>{t=t.replace(/^\/+/,"");return t.startsWith("xl/")?t:"xl/"+t.replace(/^(\.\.\/)+/,"")};
const esc=s=>N(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
function rows(ws,headerRow=1){const a=XLSX.utils.sheet_to_json(ws,{header:1,defval:"",raw:true});if(a.length<headerRow)return null;const h=a[headerRow-1].map(K);return{head:h,rows:a.slice(headerRow).map((r,i)=>({row:i+headerRow+1,values:r}))};}
function col(info,names){for(const n of names){const i=info.head.indexOf(K(n));if(i>=0)return i}return -1}
function keepSet(info,ins,per,headerRow){const ic=col(info,["INSPECTOR"]),pc=col(info,["PERIODO","PERIODO / MES"]),keep=new Set([headerRow]);for(const r of info.rows){const i=ic>=0?N(r.values[ic]):"",p=pc>=0?N(r.values[pc]):"";if(ic>=0&&ins&&K(i)!==K(ins))continue;if(pc>=0&&per&&K(p)!==K(per))continue;keep.add(r.row)}return keep}
function hideRows(xml,keep){return xml.replace(/<row\b[^>]*>/g,m=>{const n=Number((m.match(/\br="(\d+)"/)||[])[1]);if(!n||keep.has(n))return m;return /\bhidden="/.test(m)?m.replace(/\bhidden="[^"]*"/,'hidden="1"'):m.replace(/>$/,' hidden="1">')})}
async function getMeta(zip){const workbook=await zip.file("xl/workbook.xml").async("string"),relsXml=await zip.file("xl/_rels/workbook.xml.rels").async("string"),doc=new DOMParser().parseFromString(relsXml,"application/xml"),map={};for(const e of Array.from(doc.getElementsByTagName("Relationship")))map[e.getAttribute("Id")]=e.getAttribute("Target");const wdoc=new DOMParser().parseFromString(workbook,"application/xml"),paths={};for(const e of Array.from(wdoc.getElementsByTagName("sheet"))){const id=e.getAttribute("r:id")||e.getAttributeNS("http://schemas.openxmlformats.org/officeDocument/2006/relationships","id");if(id&&map[id])paths[e.getAttribute("name")]=normPath(map[id])}return{workbook,relsXml,paths}}
function removeControl(workbookXml,relsXml,zip){const m=workbookXml.match(/<sheet\b[^>]*\bname=["']CONTROL["'][^>]*\/?>/i);if(!m)return{workbookXml,relsXml};const rid=(m[0].match(/\br:id=["']([^"']+)["']/)||[])[1];workbookXml=workbookXml.replace(m[0],"");if(rid){const re=new RegExp(`<Relationship\\b[^>]*\\bId=["']${rid}["'][^>]*/?>`,'i'),rm=relsXml.match(re);if(rm){const target=(rm[0].match(/\bTarget=["']([^"']+)["']/i)||[])[1];if(target)zip.remove(normPath(target));relsXml=relsXml.replace(re,"")}}workbookXml=workbookXml.replace(/(<workbookView[^>]*\bactiveTab=")[^"]*(")/,"$11$2");return{workbookXml,relsXml}}
function removePackageParts(ct,relsXml,zip){for(const name of Object.keys(zip.files)){if(/^xl\/(vbaProject|vbaData|vbaProjectSignature)/i.test(name)||/^customUI\//i.test(name)||/^xl\/externalLinks\//i.test(name)||/^xl\/calcChain\.xml$/i.test(name))zip.remove(name)}relsXml=relsXml.replace(/<Relationship\b[^>]*(?:vbaProject|vbaProjectSignature|customUI|externalLink|calcChain)[^>]*\/?>/gi,"");ct=ct.replace(/<Override\b[^>]*(?:vbaProject|vbaProjectSignature|externalLink|calcChain)[^>]*\/?>/gi,"");ct=ct.replace(/<Override\b[^>]*PartName=["']\/xl\/workbook\.xml["'][^>]*ContentType=["']application\/vnd\.ms-excel\.sheet\.macroEnabled\.main\+xml["'][^>]*\/?>/i,`<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>`);return{ct,relsXml}}
function removeExternalReferences(workbookXml){workbookXml=workbookXml.replace(/<externalReferences\b[\s\S]*?<\/externalReferences>/gi,"");workbookXml=workbookXml.replace(/<definedName\b[^>]*>[\s\S]*?\[[\s\S]*?<\/definedName>/gi,"");return workbookXml}
function freezeAllFormulaCells(xml){return xml.replace(/<c\b([^>]*)>([\s\S]*?)<\/c>/gi,(full,attrs,body)=>{const fm=body.match(/<f\b[^>]*>([\s\S]*?)<\/f>|<f\b[^>]*\/>/i);if(!fm)return full;const v=body.match(/<v>([\s\S]*?)<\/v>/i);if(!v)return full;return `<c${attrs}><v>${v[1]}</v></c>`})}
function freezeExternalFormulaCells(xml){return xml.replace(/<c\b([^>]*)>([\s\S]*?)<\/c>/gi,(full,attrs,body)=>{const fm=body.match(/<f\b[^>]*>([\s\S]*?)<\/f>/i);if(!fm||!/[\[\]]/.test(fm[1]||""))return full;const v=body.match(/<v>([\s\S]*?)<\/v>/i);return v?`<c${attrs}><v>${v[1]}</v></c>`:full})}
function cleanCell(xml,ref,value){const re=new RegExp(`<c\\b[^>]*\\br="${ref}"[^>]*>[\\s\\S]*?<\\/c>`,'s'),m=xml.match(re);if(!m)return xml;const s=(m[0].match(/\bs="([^"]+)"/)||[])[1];return xml.replace(re,`<c r="${ref}"${s?` s="${s}"`:""} t="inlineStr"><is><t>${esc(value)}</t></is></c>`)}
function setFormula(xml,ref,formula,cached){const re=new RegExp(`<c\\b[^>]*\\br="${ref}"[^>]*>[\\s\\S]*?<\\/c>`,'s'),m=xml.match(re);if(!m)return xml;const s=(m[0].match(/\bs="([^"]+)"/)||[])[1];return xml.replace(re,`<c r="${ref}"${s?` s="${s}"`:""}><f>${esc(formula)}</f><v>${cached==null?"":cached}</v></c>`)}
function dataBySheet(wb,name,headerRow){const sh=wb.SheetNames.find(x=>K(x)===K(name));if(!sh)return null;const a=XLSX.utils.sheet_to_json(wb.Sheets[sh],{header:1,defval:"",raw:true}),h=a[headerRow-1]?.map(K)||[];return{sheet:sh,header:h,rows:a.slice(headerRow)}}
function idx(h,n){const i=h.indexOf(K(n));return i<0?null:i}
function nval(v){const n=Number(String(v??"").replace(/,/g,""));return Number.isFinite(n)?n:0}
function sumWhere(data,criteria,sumCol){if(!data)return 0;const sc=idx(data.header,sumCol);if(sc==null)return 0;let total=0;for(const r of data.rows){let ok=true;for(const [name,want] of Object.entries(criteria)){const c=idx(data.header,name);if(c!=null&&K(r[c])!==K(want)){ok=false;break}}if(ok)total+=nval(r[sc])}return total}
function tapaCellValue(wb,tapaName,ref){const sh=wb.Sheets[tapaName],a=XLSX.utils.sheet_to_json(sh,{header:1,defval:"",raw:true}),m=ref.match(/^([A-Z]+)(\d+)$/);if(!m)return"";const col=XLSX.utils.decode_col(m[1]),row=Number(m[2])-1;return a[row]?.[col]??""}
function tapaNumeric(wb,tapaName,ref){return nval(tapaCellValue(wb,tapaName,ref))}
function buildTapa(wb,xml,ins,per){const det=dataBySheet(wb,"DETALLE",1),mat=dataBySheet(wb,"MAT",9),rec=dataBySheet(wb,"RECUPERO",9),tapa=wb.SheetNames.find(x=>K(x)==="TAPA");if(!det||!mat||!rec||!tapa)return xml;
for(let r=22;r<=27;r++){const code=String(tapaCellValue(wb,tapa,`B${r}`)),q=sumWhere(det,{"Q":code,"TELECONTROL / PROTECCION":"TELECONTROL","INSPECTOR":ins,"PERIODO":per},"CANT. LCL"),p=tapaNumeric(wb,tapa,`G${r}`);xml=setFormula(xml,`F${r}`,`SUMIFS(DETALLE!$U:$U,DETALLE!$Q:$Q,$B${r},DETALLE!$C:$C,"TELECONTROL",DETALLE!$X:$X,DATOS!$B$14,DETALLE!$L:$L,DATOS!$B$28)`,q);xml=setFormula(xml,`H${r}`,`IFERROR(F${r}*G${r},0)`,q*p)}
for(let r=34;r<=39;r++){const code=String(tapaCellValue(wb,tapa,`B${r}`)),q=sumWhere(det,{"Q":code,"TELECONTROL / PROTECCION":"PROTECCION","INSPECTOR":ins,"PERIODO":per},"CANT. LCL"),p=tapaNumeric(wb,tapa,`G${r}`);xml=setFormula(xml,`F${r}`,`SUMIFS(DETALLE!$U:$U,DETALLE!$Q:$Q,$B${r},DETALLE!$C:$C,"PROTECCION",DETALLE!$X:$X,DATOS!$B$14,DETALLE!$L:$L,DATOS!$B$28)`,q);xml=setFormula(xml,`H${r}`,`IFERROR(F${r}*G${r},0)`,q*p)}
for(let r=46;r<=48;r++){const code=String(tapaCellValue(wb,tapa,`C${r}`)),q=sumWhere(mat,{"MATRICULA SAP":code,"INSPECTOR":ins,"PERIODO":per},"LIQUIDADO"),p=tapaNumeric(wb,tapa,`G${r}`);xml=setFormula(xml,`F${r}`,`SUMIFS(MAT!$J:$J,MAT!$E:$E,$C${r},MAT!$O:$O,DATOS!$B$14,MAT!$P:$P,DATOS!$B$28)`,q);xml=setFormula(xml,`H${r}`,`IFERROR(F${r}*G${r},0)`,q*p)}
for(let r=55;r<=59;r++){const code=String(tapaCellValue(wb,tapa,`C${r}`)),q=sumWhere(rec,{"MATRICULA SAP":code,"INSPECTOR":ins,"PERIODO":per},"CANTIDAD"),p=tapaNumeric(wb,tapa,`G${r}`);xml=setFormula(xml,`F${r}`,`SUMIFS(RECUPERO!$I:$I,RECUPERO!$E:$E,$C${r},RECUPERO!$L:$L,DATOS!$B$14,RECUPERO!$M:$M,DATOS!$B$28)`,q);xml=setFormula(xml,`H${r}`,`IFERROR(F${r}*G${r},0)`,q*p)}return xml}
async function buildOutput(file,ins,per){const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:"array",cellDates:true}),zip=await JSZip.loadAsync(buf),meta=await getMeta(zip);let workbookXml=removeExternalReferences(meta.workbook),relsXml=meta.relsXml,ct=await zip.file("[Content_Types].xml").async("string");({ct,relsXml}=removePackageParts(ct,relsXml,zip));({workbookXml,relsXml}=removeControl(workbookXml,relsXml,zip));workbookXml=removeExternalReferences(workbookXml);
for(const name of ["DETALLE","MAT","RECUPERO"]){const real=wb.SheetNames.find(x=>K(x)===name);if(!real||!meta.paths[real])continue;const headerRow=/^(MAT|RECUPERO)$/.test(name)?9:1,info=rows(wb.Sheets[real],headerRow);if(!info)continue;const keep=keepSet(info,ins,per,headerRow);let xml=hideRows(await zip.file(meta.paths[real]).async("string"),keep);if(name==="DETALLE")xml=freezeExternalFormulaCells(xml);zip.file(meta.paths[real],xml)}
const bares=wb.SheetNames.find(x=>K(x)==="BAREMOS");if(bares&&meta.paths[bares])zip.file(meta.paths[bares],freezeAllFormulaCells(await zip.file(meta.paths[bares]).async("string")));
for(const real of wb.SheetNames){if(!meta.paths[real]||/^(DETALLE|BAREMOS|MAT|RECUPERO|TAPA|DATOS)$/.test(K(real)))continue;const f=zip.file(meta.paths[real]);if(!f)continue;zip.file(meta.paths[real],freezeExternalFormulaCells(await f.async("string")))}
const datos=wb.SheetNames.find(x=>K(x)==="DATOS");if(datos&&meta.paths[datos]){let xml=await zip.file(meta.paths[datos]).async("string");xml=cleanCell(xml,"B14",ins);xml=cleanCell(xml,"B28",per);zip.file(meta.paths[datos],xml)}
const tapa=wb.SheetNames.find(x=>K(x)==="TAPA");if(tapa&&meta.paths[tapa]){let xml=await zip.file(meta.paths[tapa]).async("string");xml=buildTapa(wb,xml,ins,per);zip.file(meta.paths[tapa],xml)}
workbookXml=workbookXml.replace(/<calcPr\b[^>]*\/?>/i,"");zip.file("xl/workbook.xml",workbookXml);zip.file("xl/_rels/workbook.xml.rels",relsXml);zip.file("[Content_Types].xml",ct);return zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}})}
async function exportClean(){const file=$("file")?.files?.[0],ins=$("ins")?.value||"",per=$("per")?.value||"";if(!file)return alert("Carga primero el archivo Excel.");if(!ins||!per)return alert("Selecciona Inspector y Periodo antes de generar la liquidación.");if(!window.JSZip)return alert("No se cargó el motor de Excel. Actualiza la página.");try{const out=await buildOutput(file,ins,per),a=document.createElement("a");a.href=URL.createObjectURL(out);a.download=file.name.replace(/\.(xlsm|xlsb|xlsx)$/i,"")+` - ${ins.replace(/\s+/g,"_")} - ${per.replace(/\s+/g,"_")}.xlsx`;a.style.display="none";document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200);$("badge").textContent="Archivo limpio generado";$("prevbox").textContent=`Liquidación ${ins} · ${per} generada en .xlsx, sin macros, sin CONTROL y sin vínculos externos.`}catch(e){console.error(e);alert("No se pudo generar el Excel limpio: "+(e.message||e))}}
document.addEventListener("click",e=>{const t=e.target?.closest?.("#gen,#exp");if(!t)return;e.preventDefault();e.stopImmediatePropagation();exportClean()},true);
})();