(()=>{
"use strict";
const $=id=>document.getElementById(id);
const N=x=>String(x??"").trim(),K=x=>N(x).toUpperCase();
const normPath=t=>{t=String(t||"").replace(/^\/+/,"");return t.startsWith("xl/")?t:"xl/"+t.replace(/^(\.\.\/)+/,"")};
const esc=s=>N(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const num=x=>{if(typeof x==="number")return Number.isFinite(x)?x:0;const n=Number(N(x).replace(/,/g,""));return Number.isFinite(n)?n:0};
function rows(ws,headerRow){const a=XLSX.utils.sheet_to_json(ws,{header:1,defval:"",raw:true});if(a.length<headerRow)return null;const h=a[headerRow-1].map(K);return{head:h,rows:a.slice(headerRow).map((r,i)=>({row:i+headerRow+1,values:r}))};}
function col(h,names){for(const n of names){const i=h.indexOf(K(n));if(i>=0)return i}return -1}
function keepSet(info,ins,per,headerRow){const ic=col(info.head,["INSPECTOR"]),pc=col(info.head,["PERIODO","PERIODO / MES"]),keep=new Set([headerRow]);for(const r of info.rows){const i=ic>=0?N(r.values[ic]):"",p=pc>=0?N(r.values[pc]):"";if(ic>=0&&ins&&K(i)!==K(ins))continue;if(pc>=0&&per&&K(p)!==K(per))continue;keep.add(r.row)}return keep}
function hideRows(xml,keep,headerRow){return xml.replace(/<row\b[^>]*>/g,m=>{const n=Number((m.match(/\br="(\d+)"/)||[])[1]);if(!n||n<=headerRow||keep.has(n))return m;return /\bhidden="/.test(m)?m.replace(/\bhidden="[^"]*"/,'hidden="1"'):m.replace(/>$/,' hidden="1">')})}
async function meta(zip){const workbook=await zip.file("xl/workbook.xml").async("string"),relsXml=await zip.file("xl/_rels/workbook.xml.rels").async("string"),rd=new DOMParser().parseFromString(relsXml,"application/xml"),map={};for(const e of Array.from(rd.getElementsByTagName("Relationship")))map[e.getAttribute("Id")]=e.getAttribute("Target");const wd=new DOMParser().parseFromString(workbook,"application/xml"),paths={};for(const e of Array.from(wd.getElementsByTagName("sheet"))){const id=e.getAttribute("r:id")||e.getAttributeNS("http://schemas.openxmlformats.org/officeDocument/2006/relationships","id");if(id&&map[id])paths[e.getAttribute("name")]=normPath(map[id])}return{workbook,relsXml,paths}}
function removeControl(workbookXml,relsXml,zip){const m=workbookXml.match(/<sheet\b[^>]*\bname=["']CONTROL["'][^>]*\/?>/i);if(!m)return{workbookXml,relsXml};const rid=(m[0].match(/\br:id=["']([^"']+)["']/)||[])[1];workbookXml=workbookXml.replace(m[0],"");if(rid){const re=new RegExp(`<Relationship\\b[^>]*\\bId=["']${rid}["'][^>]*/?>`,'i'),rm=relsXml.match(re);if(rm){const target=(rm[0].match(/\bTarget=["']([^"']+)["']/i)||[])[1];if(target)zip.remove(normPath(target));relsXml=relsXml.replace(re,"")}}return{workbookXml,relsXml}}
function removePackages(ct,relsXml,workbookXml,zip){for(const name of Object.keys(zip.files)){if(/^xl\/(vbaProject|vbaData|vbaProjectSignature)/i.test(name)||/^customUI\//i.test(name)||/^xl\/externalLinks\//i.test(name)||/^xl\/calcChain\.xml$/i.test(name))zip.remove(name)}relsXml=relsXml.replace(/<Relationship\b[^>]*(?:vbaProject|vbaProjectSignature|customUI|externalLink|calcChain)[^>]*\/?>/gi,"");ct=ct.replace(/<Override\b[^>]*(?:vbaProject|vbaProjectSignature|externalLink|calcChain)[^>]*\/?>/gi,"");ct=ct.replace(/<Default\b[^>]*Extension=["']bin["'][^>]*ContentType=["']application\/vnd\.ms-office\.vbaProject["'][^>]*\/?>/gi,"");ct=ct.replace(/<Override\b[^>]*PartName=["']\/xl\/workbook\.xml["'][^>]*ContentType=["']application\/vnd\.ms-excel\.sheet\.macroEnabled\.main\+xml["'][^>]*\/?>/i,`<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>`);workbookXml=workbookXml.replace(/<externalReferences\b[\s\S]*?<\/externalReferences>/gi,"");workbookXml=workbookXml.replace(/<definedName\b[^>]*>[\s\S]*?\[[\s\S]*?<\/definedName>/gi,"");return{ct,relsXml,workbookXml}}
function freezeExternalFormulaCells(xml){return xml.replace(/<c\b([^>]*)>([\s\S]*?)<\/c>/gi,(full,attrs,body)=>{const fm=body.match(/<f\b[^>]*>([\s\S]*?)<\/f>/i);if(!fm||!/[\[\]]/.test(fm[1]||""))return full;const v=body.match(/<v>([\s\S]*?)<\/v>/i);return v?`<c${attrs}><v>${v[1]}</v></c>`:full})}
function setCell(xml,ref,formula,cached){const re=new RegExp(`<c\\b[^>]*\\br="${ref}"[^>]*>[\\s\\S]*?<\\/c>`,'s'),m=xml.match(re);if(!m)return xml;const s=(m[0].match(/\bs="([^"]+)"/)||[])[1];return xml.replace(re,`<c r="${ref}"${s?` s="${s}"`:""}><f>${esc(formula)}</f><v>${cached==null?"":cached}</v></c>`)}
function setText(xml,ref,value){const re=new RegExp(`<c\\b[^>]*\\br="${ref}"[^>]*>[\\s\\S]*?<\\/c>`,'s'),m=xml.match(re);if(!m)return xml;const s=(m[0].match(/\bs="([^"]+)"/)||[])[1];return xml.replace(re,`<c r="${ref}"${s?` s="${s}"`:""} t="inlineStr"><is><t>${esc(value)}</t></is></c>`)}
function sheetData(wb,name,headerRow){const real=wb.SheetNames.find(x=>K(x)===K(name));if(!real)return null;const info=rows(wb.Sheets[real],headerRow);return info?{sheet:real,...info}:null}
function sumBy(data,criteria,sumHeader){if(!data)return 0;const sc=col(data.head,[sumHeader]);if(sc<0)return 0;let total=0;for(const r of data.rows){let ok=true;for(const [name,want] of Object.entries(criteria)){const c=col(data.head,[name]);if(c<0||K(r.values[c])!==K(want)){ok=false;break}}if(ok)total+=num(r.values[sc])}return total}
function valueAt(wb,sheetName,ref){const ws=wb.Sheets[sheetName];if(!ws)return"";const m=ref.match(/^([A-Z]+)(\d+)$/);if(!m)return"";return ws[XLSX.utils.encode_cell({c:XLSX.utils.decode_col(m[1]),r:Number(m[2])-1})]?.v??""}
function formulaVal(wb,sheetName,ref){return num(valueAt(wb,sheetName,ref))}
function buildTapa(wb,xml,ins,per){const det=sheetData(wb,"DETALLE",1),mat=sheetData(wb,"MAT",9),rec=sheetData(wb,"RECUPERO",9),tapa=wb.SheetNames.find(x=>K(x)==="TAPA");if(!det||!mat||!rec||!tapa)return xml;
const laborRows=[22,23,24,25,26,27],protRows=[34,35,36,37,38,39];
for(const r of laborRows){const prest=N(valueAt(wb,tapa,`C${r}`)),q=sumBy(det,{"PRESTACION":prest,"TELECONTROL  / PROTECCION":"TELECONTROL","INSPECTOR":ins,"PERIODO":per},"CANT. \nLCL"),p=formulaVal(wb,tapa,`G${r}`);xml=setCell(xml,`F${r}`,`SUMIFS(DETALLE!$U:$U,DETALLE!$P:$P,$C${r},DETALLE!$C:$C,"TELECONTROL",DETALLE!$X:$X,DATOS!$B$14,DETALLE!$L:$L,DATOS!$B$28)`,q);xml=setCell(xml,`H${r}`,`IFERROR(F${r}*G${r},0)`,q*p)}
for(const r of protRows){const prest=N(valueAt(wb,tapa,`C${r}`)),q=sumBy(det,{"PRESTACION":prest,"TELECONTROL  / PROTECCION":"PROTECCION","INSPECTOR":ins,"PERIODO":per},"CANT. \nLCL"),p=formulaVal(wb,tapa,`G${r}`);xml=setCell(xml,`F${r}`,`SUMIFS(DETALLE!$U:$U,DETALLE!$P:$P,$C${r},DETALLE!$C:$C,"PROTECCION",DETALLE!$X:$X,DATOS!$B$14,DETALLE!$L:$L,DATOS!$B$28)`,q);xml=setCell(xml,`H${r}`,`IFERROR(F${r}*G${r},0)`,q*p)}
const matMap={46:160188,47:160496,48:480001},recMap={55:160188,56:160496,57:480001,58:970515,59:162942};
for(const [rk,sourceCode] of Object.entries(matMap)){const r=Number(rk),q=sumBy(mat,{"MATRICULA SAP":String(sourceCode),"INSPECTOR":ins,"PERIODO":per},"LIQUIDADO"),p=formulaVal(wb,tapa,`G${r}`);xml=setCell(xml,`F${r}`,`SUMIFS(MAT!$J:$J,MAT!$E:$E,${sourceCode},MAT!$O:$O,DATOS!$B$14,MAT!$P:$P,DATOS!$B$28)`,q);xml=setCell(xml,`H${r}`,`IFERROR(F${r}*G${r},0)`,q*p)}
for(const [rk,sourceCode] of Object.entries(recMap)){const r=Number(rk),q=sumBy(rec,{"MATRICULA SAP":String(sourceCode),"INSPECTOR":ins,"PERIODO":per},"CANTIDAD");xml=setCell(xml,`F${r}`,`SUMIFS(RECUPERO!$I:$I,RECUPERO!$E:$E,${sourceCode},RECUPERO!$L:$L,DATOS!$B$14,RECUPERO!$M:$M,DATOS!$B$28)`,q);xml=setCell(xml,`H${r}`,`0`,0)}
const ttele=laborRows.reduce((s,r)=>s+num(valueAt(wb,tapa,`H${r}`)),0);return xml}
function setTotals(wb,xml,ins,per){const t=wb.SheetNames.find(x=>K(x)==="TAPA");if(!t)return xml;const pairs=[[28,[22,23,24,25,26,27]],[30,[28]],[40,[34,35,36,37,38,39]],[42,[40]],[49,[46,47,48]],[51,[49]],[60,[55,56,57,58,59]],[62,[60]]];for(const [r,rs] of pairs){const formula=rs.length===1?`H${rs[0]}`:`SUM(${rs.map(x=>`H${x}`).join(":")})`;let cached=0;for(const rr of rs)cached+=num(valueAt(wb,t,`H${rr}`));xml=setCell(xml,`H${r}`,`=${formula}`.replace(/^=/,""),cached)}return xml}
async function buildOutput(file,ins,per){const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:"array",cellDates:true}),zip=await JSZip.loadAsync(buf),m=await meta(zip);let workbookXml=m.workbook,relsXml=m.relsXml,ct=await zip.file("[Content_Types].xml").async("string");({workbookXml,relsXml}=removeControl(workbookXml,relsXml,zip));({ct,relsXml,workbookXml}=removePackages(ct,relsXml,workbookXml,zip));
for(const name of ["DETALLE","MAT","RECUPERO"]){const real=wb.SheetNames.find(x=>K(x)===name);if(!real||!m.paths[real])continue;const hr=name==="DETALLE"?1:9,info=rows(wb.Sheets[real],hr);if(!info)continue;let xml=hideRows(await zip.file(m.paths[real]).async("string"),keepSet(info,ins,per,hr),hr);xml=freezeExternalFormulaCells(xml);zip.file(m.paths[real],xml)}
const datos=wb.SheetNames.find(x=>K(x)==="DATOS");if(datos&&m.paths[datos]){let xml=await zip.file(m.paths[datos]).async("string");xml=setText(xml,"B14",ins);xml=setText(xml,"B26",per);xml=setText(xml,"B27",per);xml=setText(xml,"B28",per);zip.file(m.paths[datos],xml)}
const tapa=wb.SheetNames.find(x=>K(x)==="TAPA");if(tapa&&m.paths[tapa]){let xml=await zip.file(m.paths[tapa]).async("string");xml=buildTapa(wb,xml,ins,per);xml=setCell(xml,"H28","SUM(H22:H27)",null);xml=setCell(xml,"H30","H28",null);xml=setCell(xml,"H40","SUM(H34:H39)",null);xml=setCell(xml,"H42","H40",null);xml=setCell(xml,"H49","SUM(H46:H48)",null);xml=setCell(xml,"H51","H49",null);xml=setCell(xml,"H60","SUM(H55:H59)",null);xml=setCell(xml,"H62","H60",null);zip.file(m.paths[tapa],xml)}
// remove calculation chain, but request Excel to calculate internal formulas automatically
workbookXml=workbookXml.replace(/<calcPr\b[^>]*\/?>/i,`<calcPr calcId="191029" calcMode="auto" fullCalcOnLoad="1" forceFullCalc="1" calcOnSave="1"/>`);zip.file("xl/workbook.xml",workbookXml);zip.file("xl/_rels/workbook.xml.rels",relsXml);zip.file("[Content_Types].xml",ct);return zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}})}
async function exportClean(){const file=$("file")?.files?.[0],ins=$("ins")?.value||"",per=$("per")?.value||"";if(!file)return alert("Carga primero el archivo Excel.");if(!ins||!per)return alert("Selecciona Inspector y Periodo antes de generar la liquidación.");if(!window.JSZip)return alert("No se cargó el motor de Excel. Actualiza la página.");try{const out=await buildOutput(file,ins,per),a=document.createElement("a");a.href=URL.createObjectURL(out);a.download=file.name.replace(/\.(xlsm|xlsb|xlsx)$/i,"")+` - ${ins.replace(/\s+/g,"_")} - ${per.replace(/\s+/g,"_")}.xlsx`;a.style.display="none";document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200);$("badge").textContent="Archivo limpio generado";$("prevbox").textContent=`Liquidación ${ins} · ${per} generada. MAT y RECUPERO conservan sus registros.`}catch(e){console.error(e);alert("No se pudo generar el Excel limpio: "+(e.message||e))}}
document.addEventListener("click",e=>{const t=e.target?.closest?.("#gen,#exp");if(!t)return;e.preventDefault();e.stopImmediatePropagation();exportClean()},true);
})();